config/routes.rb
Rails.application.routes.draw do
  root 'routines#top'

  resources :users

  post    '/login'      => 'sessions#create'
  get     '/login/new'  => 'sessions#new'
  delete  '/logout'     => 'sessions#destroy'
  
  resources :routines
end

app/models/routine.rb
class Routine < ApplicationRecord
  
  validates :start_time,  presence: true
  validates :end_time,    presence: true
  validates :content,     presence: true, length: { maximum: 64 }
  validates :user_id,     presence: true
  
  validate :end_time_before_start_time
  
  def end_time_before_start_time()
    if self.start_time.nil? || self.end_time.nil?
      return;
    end
    
    if self.end_time < self.start_time
      errors.add(:end_time, "は開始時刻より前に設定できません。")
    end
  end
  
  def start_time_str
    start_time.nil? ? nil : start_time.strftime("%H:%M")
  end
  
  def end_time_str
    end_time.nil? ? nil : end_time.strftime("%H:%M")
  end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  
  def top
    if !logged_in?
      redirect_to controller: :users, action: :new;
    end
    
    #データベースに保存された日付(2000-01-01)と同様の値を固定値としている
    hh = Time.current.strftime("%H").to_i;
    mm = Time.current.strftime("%M").to_i;
    time = DateTime.new(2000, 1, 1, hh, mm, 00, "+09:00")
    
    #開始時刻以上かつ終了時刻未満のレコードを検索
    @routines = Routine.where('start_time <= ? AND ? < end_time', time, time);
  end
  
  def index
    #開始時刻が早い順かつ終了時刻が早い順
    @routines = Routine.where(user_id: current_user.id).order(:start_time=>:asc, :end_time=>:asc)
  end
  
  def show
    @routine = Routine.find_by(id: params[:id], user_id: current_user.id);
    if @routine.nil?
      redirect_to controller: :routines, action: :index
    end
  end

  def new
    @routine = Routine.new;
  end
  
  def create
    @routine = Routine.new(routine_params);
    if @routine.save
      redirect_to controller: :routines, action: :index
    else
      flash.now[:danger] = @routine.errors.full_messages.first
      render action: :new
    end
  end
  
  def edit
    @routine = Routine.find_by(id: params[:id], user_id: current_user.id);
    if @routine.nil?
      redirect_to controller: :routines, action: :index
    end
  end
  
  def update
    @routine = Routine.find_by(id: params[:id], user_id: current_user.id);
    if @routine.update(routine_params);
      flash[:success] = "保存しました。";
      redirect_to controller: :routines, action: :index
    else
      flash.now[:danger] = @routine.errors.full_messages.first
      render controller: :routines, action: :edit
    end
  end
  
  def destroy
    @routine = Routine.find_by(id: params[:id], user_id: current_user.id);
    
    if @routine.nil?
      redirect_to controller: :routines, action: :edit
    else
      @routine.destroy;
      flash[:success] = "削除しました。";
      redirect_to controller: :routines, action: :index
    end
  end
  
    private
    
    # ストロングパラメータ
    def routine_params
      #paramsの中身 => {routine: {id: "", start_time: ""}...}からpermitで指定した値を抽出
      params.require(:routine).permit(:id, :content)
      .merge(
        start_time: Time.zone.parse("2000-01-01 #{params[:routine][:start_time]}"), 
        end_time: Time.zone.parse("2000-01-01 #{params[:routine][:end_time]}"), 
        user_id: current_user.id
      )
    end
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/routines/_form.html.erb
<%= form_with(model: @routine, local: true) do |form| %>

  <%= form.label :start_time, "開始時刻" %>
  <%= form.time_field :start_time %>
  
    <%= form.label :end_time, "終了時刻" %>
  <%= form.time_field :end_time %>
  
  <%= form.label :content, "内容" %>
  <%= form.text_field :content %>

  <%= form.submit yield(:button_text),  data: { "disable-with": yield(:button_text) } , class: 'btn' %>
<% end %>

app/views/routines/edit.html.erb
<% provide(:button_text, '保存') %>
<%= render 'form' %>

app/views/routines/index.html.erb
<%= javascript_pack_tag 'routines/index' %>

<table id="index">
  <thead>
    <tr>
      <th class="column-no">No</th>
      <th class="column-start-time">開始時刻</th>
      <th class="column-end-time">終了時刻</th>
      <th class="column-content">内容</th>
    </tr>
  <thead>
  <tbody>
    <% @routines.each_with_index do |routine, i| %>
      <tr data-id=<%= routine.id %>>
        <td><%= (i + 1) %></td>
        <td><%= routine.start_time_str %></td>
        <td><%= routine.end_time_str %></td>
        <td><%= routine.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/routines/new.html.erb
<% provide(:button_text, '保存') %>
<%= render 'form' %>

app/views/routines/show.html.erb
<div class="show-content">
  <p class="show-content-label">開始時刻</p>
  <p class="show-content-text"><%= @routine.start_time_str %></p>
  
  <p class="show-content-label">終了時刻</p>
  <p class="show-content-text"><%= @routine.end_time_str %></p>
  
  <p class="show-content-label">内容</p>
  <p class="show-content-text"><%= @routine.content %></p>
  
  <%= link_to "編集",  edit_routine_path, { class: "btn" } %>
  <%= link_to "削除",  routine_path, { method: "delete", class: "btn" } %>
</div>

app/views/routines/top.html.erb
<div class="#">
  <table id="index">
  <thead>
    <tr>
      <th id="clock" class="clock"></th>
    </tr>
  </thead>
  <tbody>
    <% @routines.each_with_index do |routine, i| %>
      <tr>
        <input class="end_time" type="hidden" value=<%= routine.end_time_str %>>
        <td><%= routine.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  
</div>

<%= javascript_pack_tag 'routines/home', defer: true %>