config/routes.rb
Rails.application.routes.draw do
  root 'routines#top'

  resources :users

  post    '/login'      => 'sessions#create'
  get     '/login/new'  => 'sessions#new'
  delete  '/logout'     => 'sessions#destroy'
  
  resources :routines
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>RoutineMaker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
    <header id="header">
      <% if logged_in? %>
        <div class="header-logo">
          <%= link_to "RoutineMaker", root_path %>
        </div>
        <div class="header-menus">
          <%= link_to "TOP", root_path %>

          <%= link_to "新規作成",   new_routine_path %>
          <%= link_to "一覧",       routines_path %>
          <%= link_to "ログアウト", logout_path, method: :delete %>
        </div>
      <% else %>
        <div class="header-logo">
          <%= link_to "RoutineMaker", new_user_path %>
        </div>
        <ul class="header-menus">
          <li>
            <%= link_to "ログイン", login_new_path %>
          </li>
        </ul>
      <% end %>
    </header>
  <body>
    <div class="body-content">
      <%= render 'shared/flash_messages' %>
      <div class="wrapper">
        <%= yield %>
      </div>
    </div>
  </body>
</html>